spring:
  # Cannot determine embedded database driver class for database type NONE
  datasource:  
    # Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
    url: jdbc:mysql://127.0.0.1:3306/imooc-study?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  # No Spring Session store is configured: set the 'spring.session.store-type' property
  session:
    store-type: none
# 禁用 身份认证
security:
  basic:
    enabled: false